### ISSUE TITLE
Bulma CSS tag class conflicts with Prettier CSS

### ISSUE THREAD

**Issue by sukima** [SoftwareBrothers/better-docs#114]
Prettier adds the class `tag` to HTML tags when doing syntax highlighting but it seems this is the same name Bulma CSS uses for something else causing a poorly rendered output:

![Screen Shot 2020-10-26 at 13 22 50](https://user-images.githubusercontent.com/70075/97205838-60195580-178e-11eb-9cf4-905143efab4a.png)

**Comment by sukima** [comment]
### Work around

Use this custom CSS: (`styles/custom.css`)

```css
pre code .tag {
  background-color: inherit;
  border-radius: 0;
  color: #c66;
  display: inline;
  font-size: inherit;
  height: inherit;
  line-height: inherit;
  padding-left: 0;
  padding-right: 0;
  white-space: nowrap;
}
```

You can include this via the static files:

```json
{
  "templates": {
    "default": {
      "staticFiles": {
        "include": ["./styles"]
      }
    },
    "better-docs": {
      "css": "custom.css"
    }
  }
}
```
