### ISSUE TITLE
Adjust sidebar size

### ISSUE THREAD

**Issue by wronrohn** [SoftwareBrothers/better-docs#167]
How can I adjust the size of the left Sidebar? I noticed that it is 240px currently. I tried making a ```styles.css``` on my root directory where I tried to override the CSS, but that didn't seem to work.

**Comment by paweldrozd** [comment]
Unfortunately it works only if you put your css file into any director and include it:

```css
/* /docs-src/docs.styles.css */
#main>.sidebar {
  width: auto;
  min-width: 240px;
}
```


```json
//jsdoc.json
{
  // shrinked
  "templates": {
    "default": {
      "staticFiles": {
        "include": [
          "./docs-src"
        ]
      }
    },
    "better-docs": {
      "css": "docs.styles.css",
    }
  }
}
```
